image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  ASPNETCORE_ENVIRONMENT: Development
  DOTNET_USE_POLLING_FILE_WATCHER: "1"
  IMAGE_NAME: $CI_REGISTRY_IMAGE/kubysistestbackend:dev

stages:
  - build
  - push
  - deploy

before_script:
  - apk add --no-cache bash curl
  - echo "Docker daemon is ready."
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME -f ./KubysisTestBackend/Dockerfile .
    

push:
  stage: push
  script:
    - docker push $IMAGE_NAME
    

deploy:
  stage: deploy
  image: docker/compose:stable
  script:
    - docker-compose -f docker-compose.yml pull
    - docker-compose -f docker-compose.yml up -d
