version: '3.9'

services:
  kubysistestbackend:
    image: $CI_REGISTRY_IMAGE/kubysistestbackend:dev
    container_name: kubysistestbackend
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      DOTNET_USE_POLLING_FILE_WATCHER: ${DOTNET_USE_POLLING_FILE_WATCHER:-1}
    volumes:
      - ./vsdbg:/remote_debugger:rw
      - $HOME/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - $HOME/.aspnet/https:/root/.aspnet/https:ro
    entrypoint: ["dotnet", "/VSTools/DistrolessHelper/DistrolessHelper.dll", "--wait"]
